version: '3'
services:
  catalog:
    image: catalog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db.properties:/cfg/config.property
  database:
    image: postgres
    environment:
      PGUSER: "${POSTGRES_USER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
